name: Setup Kubernetes Cluster on GCP

on:
  push:
    branches:
      - mra/setup-automation  # oder der Branch, der verwendet werden soll

jobs:
  setup-cluster:
    runs-on: ubuntu-latest

    steps:
      # Check out repositories
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install needed software
      - name: Install Terraform (v1.9.0+)
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          sudo apt update && sudo apt install terraform=1.9.0-1

      - name: Install Kops (v1.31.0+)
        run: |
          curl -LO https://github.com/kubernetes/kops/releases/download/v1.31.0/kops-linux-amd64
          chmod +x kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
          sudo apt update && sudo apt install google-cloud-sdk

      # Set up gcp accessand enable gcp apis
      - name: Enable required GCP APIs
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud services enable compute.googleapis.com \
                                container.googleapis.com \
                                storage.googleapis.com

      # Authentication at google cloud
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth application-default login

      # cd in directory
      - name: CD in Repo dir
        run: cd quick-k8s-cluster

      # Init terraform
      - name: Terraform Init
        run: terraform init

      # Create cluster
      - name: Run up-cluster.sh
        run: |
          chmod +x ./up-cluster.sh
          ./up-cluster.sh advanced-cloud-prototyping

      # Call other action for installing oxn on recent creaged cluster
      #- name: Trigger oxn installation
      #  run: |
