apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      nodeSelector:
        app: oxn-host
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: backend-storage
          mountPath: /mnt/oxn-data
        - name: analysis-datastore
          mountPath: /mnt/analysis-datastore
        env:
        - name: ANALYSIS_URL
          value: "http://analysis-module:8001"
        - name: OXN_RESULTS_PATH
          value: "/mnt/oxn-data"
        - name: OXN_ANALYSIS_PATH
          value: "/mnt/analysis-datastore"
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-module-backend-pvc
      - name: analysis-datastore
        persistentVolumeClaim:
          claimName: analysis-module-analysis-datastore-pvc