apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.clusterRole }}-cluster-admin
  apiGroup: rbac.authorization.k8s.io