from enum import Enum

class AnalysisStatus(Enum):
    ANALYSIS_DATA_PATH_NOT_FOUND = "ANALYSIS_DATA_PATH_NOT_FOUND"
    FINISHED = "FINISHED"
    NOT_STARTED = "NOT_STARTED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    IN_PROGRESS = "IN_PROGRESS"
    NOT_ENABLED = "NOT_ENABLED"
